version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - mnd
    - varnamelen
  settings:
    lll:
      line-length: 170
    revive:
      rules:
        - name: dot-imports
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
